@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

# RECADOS
### Exibe todos os recados
GET {{baseUrl}}/recados/?limit=10&offset=1
### Exibe apenas um recado
GET {{baseUrl}}/recados/40/
### Cria um recado
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "texto": "Amora para Raven",
  "paraId": 18
}

### Atualiza um recado pelo id
PATCH  {{baseUrl}}/recados/40/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "lido": true
}

### Apaga um recado com id 2
DELETE  {{baseUrl}}/recados/40/
Authorization: Bearer {{authToken}}


###################


# PESSOAS
### Exibe todas as pessoas
GET {{baseUrl}}/pessoas/
Authorization: Bearer {{authToken}}
# ?limit=10&offset=10
### Exibe apenas uma pessoa
GET {{baseUrl}}/pessoas/6/
Authorization: Bearer {{authToken}}
### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "nome": "Raven",
  "password": "123456",
  "email": "raven@gmail.com"
}

### Atualiza uma pessoa pelo id
PATCH  {{baseUrl}}/pessoas/18/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "nome": "KaioAutoAtt"
}

### Apaga uma pessoa com id 9
DELETE  {{baseUrl}}/pessoas/18/
Authorization: Bearer {{authToken}}


###################


# AUTH
### Loga o usuario
# @name authenticate
POST  {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "amora@gmail.com",
  "password": "123456"
}